### PR TITLE
Upgrades PCS2 to use wxWidgets 3.0.2, in addition to some much needed…

### PR DESCRIPTION
**Pull request by z64555**
… project-related organization.

Be advised that this is still very much WIP, as there's a number of things that need fixing before it'll build correctly.

### CODE REVIEW

**Comment by TRBlount** [comment]
We should also look into updating the wxWidgets version used by PCS2 and making the relevant changes.

**Comment by z64555** [comment]
@DahBlount that comment sounded like you ignored the PR title :P

**Comment by TRBlount** [comment]
yeah... lrn2read

**Comment by z64555** [comment]
Closing due to newer/better PR's available.

**Pull request closed without merging**
