### PR TITLE
Fix for paths without trailing slashes

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by niffiwan** [comment]
considering how annoying I've found this bug to be I'd like to merge it :) However, I can't build at the moment; what version of SDL does it require? 2.0.0+?

**Comment by asarium** [comment]
SDL? AFAIK PCS doesn't use SDL.

**Comment by niffiwan** [comment]
Oh; https://github.com/scp-fs2open/PCS2/blob/master/src/CMakeLists.txt#L166

Maybe I've got the wrong version of wxWidgets then?

`-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_gtk2u_core-3.0;-lwx_baseu-3.0;-lwx_gtk2u_gl-3.0;-lwx_gtk2u_adv-3.0 (found version "3.0.0")`

**Comment by asarium** [comment]
Oh, I didn't have to configure anything and just assumed that only wxWidgets is required because I didn't need to add the paths on Windows.

I think you need wxWidgets 2.8. 3.0 apparently doesn't work right.

**Comment by niffiwan** [comment]
right, finally got it compiling, see #6

**Comment by niffiwan** [comment]
and now that I can test; LGTM!

**Pull request merged**
