### PR TITLE
Fix/wx3 tweaks

### PR DESCRIPTION
**Pull request by niffiwan**

### CODE REVIEW

**Comment by niffiwan** [comment]
per comments in #10

**Comment by z64555** [comment]
fabs is not a member of std::, Had one of the CI's complain about it in the fs2open repo

**Comment by niffiwan** [comment]
[Sure looks like it is](http://en.cppreference.com/w/cpp/numeric/math/fabs), need to include `<cmath>`. I successfully compiled & ran this branch on Windows & Linux

**Comment by z64555** [comment]
I must be derpin then -_-

**Comment by niffiwan** [comment]
@z64555 is there anything else needed before merging?

**Pull request merged**
